# zsh config, mirroring the oh-my-zsh setup from nix/home/steve.nix.
# Installed to ~/.zshrc by install/dotfiles.sh.

# ---- history ----
HISTFILE=~/.zsh_history
HISTSIZE=50000
SAVEHIST=50000
setopt SHARE_HISTORY HIST_IGNORE_DUPS HIST_IGNORE_SPACE

# ---- completion ----
autoload -Uz compinit && compinit
zstyle ':completion:*' menu select

# ---- plugins (pacman-installed, not oh-my-zsh) ----
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh 2>/dev/null
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null

# ---- prompt ----
autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats ' (%b)'
setopt PROMPT_SUBST
PROMPT='%F{blue}%~%f%F{green}${vcs_info_msg_0_}%f %# '

# ---- tools ----
command -v zoxide >/dev/null && eval "$(zoxide init zsh)"
command -v direnv >/dev/null && eval "$(direnv hook zsh)"
[ -f /usr/share/fzf/key-bindings.zsh ] && source /usr/share/fzf/key-bindings.zsh
[ -f /usr/share/fzf/completion.zsh ] && source /usr/share/fzf/completion.zsh

# ---- aliases (match the Nix side) ----
alias ls='eza'
alias ll='eza -l --git'
alias la='eza -la --git'
alias cat='bat --paging=never'
alias lg='lazygit'

export EDITOR=vim
export VISUAL=vim
